[mypy]
python_version = 3.12
strict = True
ignore_missing_imports = True
plugins = pydantic.mypy

[mypy-duckdb.*]
ignore_missing_imports = True

[mypy-diskcache.*]
ignore_missing_imports = True

[mypy-yfinance.*]
ignore_missing_imports = True

[mypy-praw.*]
ignore_missing_imports = True

[mypy-vaderSentiment.*]
ignore_missing_imports = True

[mypy-weasyprint.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True
